# -*- coding: utf-8 -*-
"""langchain_language_translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjPXhzR-RSals1OG-fvAd6PFRvM7aC2c
"""

import os
from dotenv import load_dotenv
losd_dotenv()

os.environ["GROQ_API_KEY"]=os.getenv("GROQ_API_KEY")
os.environ["LANGCHAIN_TRACING_V2"]='true'
os.environ["LANGCHAIN_PROJECT"]=os.getenv("LANGCHAIN_PROJECT")

from lanhchain_core.messages import SystemMessage , HumanMessage
messages=[
    SystemMessage(content="translate the follwing english to french")
    HumanMessage(content="hello how are u")
]

result=model.invoke(messages)

from langchain_core.output_parsers import StrOutputParser
parser=StrOutputParser()

from langchain_groq import ChatGroq
model=ChatGroq(model="gamma-2b" , groq_api_key=api_key)

from langchain_core.prompts import ChatPromptTemplate
generic_template="transalate follwing into {language}"
template=ChatPromptTemplate.from_messages(

    [
        ("system",generic_template)
        ("user","{text}")
    ]
)

chain=promt|model|parser

chain.invoke({"language":"French","text":"Hello"})